"""Make comment description nullable

Revision ID: 698de42fb13f
Revises: 6d3beaaa00ba
Create Date: 2026-03-08 16:52:39.780489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '698de42fb13f'
down_revision: Union[str, Sequence[str], None] = '6d3beaaa00ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_ibfk_1'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_ibfk_2'), 'files', type_='foreignkey')
    op.drop_column('files', 'task_id')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('files_ibfk_2'), 'files', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('files_ibfk_1'), 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
